import type { Metadata } from "next";
import  {Source_Sans_3,Fira_Sans} from 'next/font/google'
import "./globals.css";

const mainFont = Source_Sans_3({
  subsets: ["latin"],
  display: "swap",
});

const subFont = Fira_Sans({
  subsets: ["latin"],
  display: "swap",
  weight:"700",
});

export const metadata: Metadata = {
  title: "Dashboard App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mainFont.className} ${subFont.className}`}>
        {children}
      </body>
    </html>
  );
}
